name: Selenoid Tests Workflow
on:
  push:
    branches:
      - master
jobs:
  checkout-and-print-tree:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Print project tree
        run: tree .