name: Selenoid Tests Workflow
on:
  push:
    branches:
      - master
jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: actions/checkout@v4
      - name: Pull selenoid image
        run: docker pull selenoid/chrome:128.0
      - name: Run tests in docker
        run: docker compose up --build --exit-code-from test_docker